Removed test that triggered QHull error
=== RUN   TestGridCreate
Calling gdal.GridCreate
ERROR 6: GDALTriangulationCreateDelaunay() unavailable since GDAL built without QHull support
    algorithms_test.go:75: GridCreate: Failure Error
--- FAIL: TestGridCreate (0.30s)